package com.example.actividadfinalaccesodatos_adriansabinoperez.Repository

import com.example.actividadfinalaccesodatos_adriansabinoperez.Entity.EmpresaDesarrolladora
import org.springframework.data.mongodb.repository.MongoRepository

interface EmpresaDesarrolladoraRepository : MongoRepository<EmpresaDesarrolladora, String>
